import "../styles/globals.css";
import Head from "next/head";
import Script from "next/script";

function MyApp({ Component, pageProps }) {
  return (
    <Component {...pageProps}>
      <Head>
        <title>Create Next App</title>
        <meta
          name="viewport"
          content="width=device-width, user-scalable=yes, initial-scale=1, maximum-scale=1 viewport-fit=cover"
        />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="../defaultScript/index.js" />
    </Component>
  );
}

export default MyApp;
